<?php

namespace App\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceProductRepository extends EntityRepository
{
}
