<?php

namespace App\InvoiceBundle\Entity;
use App\CoreBundle\Entity\EntityRepository;

/**
 * InvoiceTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceTaskRepository extends EntityRepository
{
}
