<?php

namespace App\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceProductTaxesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceProductTaxesRepository extends EntityRepository
{
}
