<?php

namespace App\TaskBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;
use App\ProjectBundle\Entity\Category;

/**
 * TaskPresetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskPresetRepository extends EntityRepository
{
    public function getByCategory(Category $category)
    {
        $query_builder = $this->getDefaultQueryBuilder();
        $query_builder->andWhere($this->column('category').' = :category')
                        ->setParameter('category', $category)
                        ->orderBy($this->column('order'), 'ASC');

        return $query_builder->getQuery()->getResult();
    }
}
