<?php

namespace App\EmailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    public function getEmailsByPerson($personId) {

        $qb = $this->createQueryBuilder('em')
            ->innerJoin('em.person', 'p')
            ->where('p.id = :person_id')
            ->setParameter('person_id', $personId);
        return $qb->getQuery()->getResult();

    }
}
