<?php

namespace App\EmailBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;

/**
 * EmailTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTypeRepository extends EntityRepository
{
    
}