<?php

namespace App\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountCurrencyRepository extends EntityRepository
{
}
