<?php
/**
 * Created by PhpStorm.
 * User: Maciej
 * Date: 03.02.14
 * Time: 15:19
 */

namespace App\FormBundle\Form\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class FiltersType extends AbstractType
{
    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub

        $available_filters = [];
        foreach($form->all() as $child){
            $child_name = $child->getName();
            $wrapper_name = $child_name.'-wrapper';
            /** @var FormView $child_view */
            $child_view = $view->children[$child_name];
            $child_view->vars['filter_wrapper'] = $wrapper_name;
            $available_filters[$wrapper_name] = $child_view->vars['label'];
        }

        $view->vars['filters'] = $available_filters;
    }


    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'filters';
    }

} 