<?php

namespace App\PlaceBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    public function getDefaultQueryBuilder()
    {
        $queryBuilder =  parent::getDefaultQueryBuilder();
        $queryBuilder->orderBy($this->column('importance'), 'DESC');

        return $queryBuilder;
    }


}
