<?php

namespace App\PersonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonImageRepository extends EntityRepository
{
}
