<?php

namespace App\AccountProductBundle\Entity;

use App\AccountBundle\Entity\AccountProfile;
use App\CoreBundle\Entity\EntityRepository;


/**
 * AccountProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountProductRepository extends EntityRepository
{
    public function getAccountQueryBuilder(AccountProfile $accountProfile)
    {
        $query_builder = $this->getDefaultQueryBuilder();
        $query_builder->join($this->column('product'), 'Product')
                    ->join($this->column('account'), 'Account')
                    ->andWhere('Account = :account')
                    ->setParameter('account', $accountProfile);

        return $query_builder;
    }
    
    public function getQueryBuilderByCriteria(array $criteria = array())
    {
        $qb = parent::getQueryBuilderByCriteria($criteria);

        if (isset($criteria['profileId']) && $criteria['profileId'] !== '' && $criteria['profileId'] !== null) {
            $qb
                    ->andWhere($this->column('account') . ' = :account')
                    ->setParameter('account', $criteria['profileId']);
            ;
        }

        return $qb
                        ->leftJoin($this->column('product'), 'product')
                        ->leftJoin('product.brandGroup', 'brandGroup')
        ;
    }
}
