<?php

namespace App\StatusBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;

/**
 * StatusGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{

    public function getDefaultQueryBuilder()
    {
        $query_builder = parent::getDefaultQueryBuilder();
        $query_builder->orderBy($this->column('name'), 'ASC');

        return $query_builder;
    }

    public function getQueryBuilderByCriteria(array $criteria = array())
    {
        $qb = parent::getQueryBuilderByCriteria($criteria);

        if (isset($criteria['classname']) && $criteria['classname'] !== '' && $criteria['classname'] !== null) {
            $qb
                    ->andWhere($this->column('className') . ' = :className')
                    ->setParameter('className', $criteria['classname']);
            ;
        }

        return $qb
                        ->leftJoin($this->column('statuses'), 'statuses')
                        ->add('select', 'statuses', true)
        ;
    }

}