<?php

namespace App\PaymentBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
}
