<?php

namespace App\PurchaseBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;


/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class PurchaseRepository extends EntityRepository
{
    public function getDefaultQueryBuilder()
    {
        $query_builder = parent::getDefaultQueryBuilder();
        $query_builder->orderBy($this->column('editDate', 'desc'));

        return $query_builder;
    }
    
    public function getQueryBuilderByCriteria(array $criteria = array())
    {
        $qb = parent::getQueryBuilderByCriteria($criteria);

        return $qb
                        ->leftJoin($this->column('accountProfile'), 'accountProfile')
                        ->leftJoin($this->column('supplier'), 'supplier')
        ;
    }

}
