parameters:
#    app_media.example.class: App\MediaBundle\Example

services:
#    app_media.example:
#        class: %app_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
