<?php
namespace App\InvoiceBundle\Entity\Returns;

use App\CoreBundle\Entity\EntityRepository;

/**
 * ProductReturnReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductReturnReasonRepository extends EntityRepository
{
}
