parameters:
    jms_i18n_routing.pattern_generation_strategy.class: App\LanguageBundle\Router\DefaultPatternGenerationStrategy

services:
    jms_i18n_routing.pattern_generation_strategy.default:
        class: %jms_i18n_routing.pattern_generation_strategy.class%
        arguments: [%jms_i18n_routing.strategy%,@translator, %jms_i18n_routing.locales%, %kernel.cache_dir%, %jms_i18n_routing.catalogue%,%jms_i18n_routing.default_locale%,@doctrine.orm.default_entity_manager]
    languages.extension:
        class: App\LanguageBundle\Twig\LanguageExtension
        tags:
            -  { name: twig.extension }
        arguments: [@app.locales_provider]
    app.locales_provider:
        class: App\LanguageBundle\Locale\AvailableLocalesProvider
        arguments: [@doctrine.orm.entity_manager]
    lexik_translation.data_grid.request_handler:
        class: App\LanguageBundle\Util\DataGrid\DataGridRequestHandler
        arguments: [@lexik_translation.trans_unit.manager, @lexik_translation.translation_storage, @app.locales_provider, %lexik_translation.managed_locales%]
    lexik_translation.form.handler.trans_unit:
        class: App\LanguageBundle\Form\Handler\TransUnitFormHandler
        arguments: [@lexik_translation.trans_unit.manager, @lexik_translation.file.manager, @lexik_translation.translation_storage, @app.locales_provider, %lexik_translation.managed_locales%, %kernel.cache_dir%]
    lexik_translation.data_grid.formatter:
        class: App\LanguageBundle\Util\DataGrid\DataGridFormatter
        arguments: [@app.locales_provider, %lexik_translation.managed_locales%, %lexik_translation.storage.type%]
    lexik_translation.filter.languagefilter:
        class:  App\LanguageBundle\Filter\LanguageFilter
        parent: app_core.filter.filter