<?php

namespace App\CompanyBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;


/**
 * CompanyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonCompanyRepository extends EntityRepository {

    public function getCompanyShippingAddress($companyId) {

        $em = $this->_em;
        $result = array();
        $q = $em->createQuery('Select a From App\AddressBundle\Entity\Address a
                                            Inner join a.companies c
                                            where a.isShipping=1
                                            and c.id='.$companyId);
        $resultat = $q->getResult();
        $result = $this->trasformData($resultat);
        return $result;

    }

    public function getCompanyBillingAddress($companyId) {

        $em = $this->_em;
        $result = array();
        $q = $em->createQuery('Select a From App\AddressBundle\Entity\Address a
                                            Inner join a.companies c
                                            where a.isBilling=1
                                            and c.id='.$companyId);
        $resultat = $q->getResult();
        $result = $this->trasformData($resultat);
        return $result;

    }

    private function trasformData($resultat) {
        $result = array();
        if(!empty($resultat)) {
            $i=0;
            foreach ($resultat as $res) {
                $result[$i]['id'] = $res->getId();
                $country = $res->getCountry();
                $result[$i]['country'] = empty($country) == true ? '' : $country->getName();
                $province = $res->getProvince();
                $result[$i]['province'] = empty($province) == true ? '' : $province->getName();
                $region = $res->getRegion();
                $result[$i]['region'] = empty($region) == true ? '' : $region->getName();
                $result[$i]['postcode'] = $res->getPostcode();
                $result[$i]['city'] = $res->getCity();
                $result[$i]['street'] = $res->getStreet();
                $result[$i]['building'] = $res->getBuilding();
                $result[$i]['suite'] = $res->getSuite();
                $result[$i]['po'] = $res->getPo();
                $result[$i]['contact'] = $res->getContact();
            }
        }

        return $result;
    }
}
