<?php

namespace App\CompanyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyImageRepository extends EntityRepository
{
}
