<?php

namespace App\CompanyBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getDefaultQueryBuilder()
    {
        $query_builder = parent::getDefaultQueryBuilder();
        $query_builder->orderBy($this->column('name'), 'ASC');

        return $query_builder;
    }

    public function getCompanyList($params)
    {
        try {
        	
	        $qb = $this->getDefaultQueryBuilder();
	        //$qb->where($qb->expr()->like($this->column('name'), ':name'))->setParameter('name', "Banque");
			//print_r($qb->getSqlQuery()); die;
            return $qb->getQuery()->getResult();

        }
        catch (\Doctrine\ORM\NoResultException $e) {
            throw new Exception('Caught exception: '.$e->getMessage());
        }

    }
    
    public function getQueryBuilderByCriteria(array $criteria = array())
    {
        $qb = parent::getQueryBuilderByCriteria($criteria);

        return $qb
                        ->leftJoin($this->column('companyType'), 'companyType')
                        ->leftJoin($this->column('sector'), 'sector')
//                        ->leftJoin('phones.phoneType', 'phoneType')
//                        ->leftJoin($this->column('phones'), 'phones')
//                        ->leftJoin($this->column('addresses'), 'addresses')
        ;
    }

}
