<?php

namespace App\CompanyBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;

/**
 * CompanyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyTypeRepository extends EntityRepository
{
}
