<?php

namespace App\LanguageBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
	/**
     * Get the available locales from the database
     *
     * @todo: Cache this if it gets too slow, by apc
     * @return array locales
     */
    public function getLocales()
    {
        $data = array();
        $languages = $this->findBy(array('backend' => true));
        foreach($languages as $language){
            $data[] = $language->getIso();
        }
        return $data;
    }

    /**
     * Get the available activated locales from the database
     *
     * @todo: Cache this if it gets too slow, by apc
     * @return array locales
     */
    public function getFrontendLocales()
    {
        $data = array();
        $languages = $this->findBy(array('frontend' => true, 'backend' => true));
        foreach($languages as $language){
            $data[] = $language->getIso();
        }
        return $data;
    }
}
