<?php

namespace App\ProductBundle\Entity;

use App\CoreBundle\Entity\EntityRepository;

/**
 * ProductTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository {

    public function getProductInfo($productId) {

        $em = $this->_em;
        $result = array();
        $q = $em->createQuery('Select p From App\ProductBundle\Entity\Product p
                                            where p.id='.$productId);
        $resultat = $q->getResult();
        $result = $this->trasformData($resultat[0]);
        return $result;

    }

    private function trasformData($resultat) {
        $result = array();

        if ($resultat->getPrice()) {
            $price = $resultat->getPrice()->getSellPrice();
            $result['price']=$price;
            $discaunt = $resultat->getPrice()->getDiscaunt();
            $result['discaunt'] = $discaunt;
        }
        else {
            $result['price']=0;
            $result['discaunt'] = 0;
        }

        $buff = array();
        if ($resultat->getTaxes()) {
            $taxes = $resultat->getTaxes();

            $i = 0;
            foreach($taxes as $tax) {
                $buff[$i]['id'] = $tax->getId();
                $buff[$i]['name'] = $tax->getName().' ('.$tax->getRate().'%)';
                $buff[$i]['rate'] = $tax->getRate();
                $i++;
            }
        }

        $result['taxes'] = $buff;

        return $result;
    }
}
