<?php

namespace App\TaxBundle\Entity;
use App\CoreBundle\Entity\EntityRepository;

/**
 * TaxationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxationRepository extends EntityRepository
{
}
